### ISSUE TITLE
تحديث الاضافة

### ISSUE THREAD

**Issue by ghost** [zombiB/zombib.github.io#1]
مرحبا حبيبنا الف شكر على الاضافة الرائعة ملاحظ انها تحتاج تحديث خصوصا لعناوين سيما كلوب وايجي بست كذالك لصفحات الرياضة مباشر 🙏 شاكر وممتن

**Comment by zombiB** [comment]
مرحبا بك ، للأسف التغيير الي صار في كود المواقع يحتاج بعض الوقت لاصلاحه سأحاول قريبا إرسال تحديث جديد
